== Connectivity Testing
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Prerequisites

* Be familiar with how to define a connection for your module. +
See xref:connections.adoc[Connections] for more information.
* To create connectivity tests, add the `mtf-tools` dependency to your project:
+
[source,xml,linenums]
----
<dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>mtf-tools</artifactId>
    <version>1.0.0-BETA3</version>
    <classifier>mule-plugin</classifier>
    <scope>test</scope>
</dependency>
----
* Connectivity Testing is available since Mule Runtime version 4.2.0. +
If your connector has a minMuleVersion prior to 4.2.0, add the `minMuleVersion` to your connectivity testing suite: `<munit:config name="connectivity-testing-suite" minMuleVersion="4.2.0"/>`


== Test Connectivity

The `test-connectivity` processor establishes a connection using the given configuration. If testing connectivity with the given configuration fails, the processor will fail with the proper exception, description
and error type (if present),

=== Successful Connection

When you test that a connection is valid, you are validating that the processor does not fail. A successful connection test looks as follows:

.Valid connection
[source,xml,linenums]
----
<munit:test name="validConnectionTest">
    <munit:execution>
        <mtf:test-connectivity config-ref="validConnection"/>
    </munit:execution>
</munit:test>
----

=== Invalid connection

When a connection fails, the processor fails. Therefore, to test an invalid connection, expect the error in the test:

.Invalid connection
[source,xml,linenums]
----
<munit:test name="invalidConnectionTest"
            expectedException="com.example.MyConnectionException"
            expectedErrorDescription="An error occurred while connecting">
    <munit:execution>
        <mtf:test-connectivity config-ref="invalidConnection"/>
    </munit:execution>
</munit:test>
----

If the connection fails with an error type, you can expect it as well:

.Invalid connection with error type
[source,xml,linenums]
----
<munit:test name="invalidConnectionWithErrorTypeTest"
            expectedException="com.example.MyConnectionException"
            expectedErrorType="EXAMPLE:INVALID_CREDENTIALS"
            expectedErrorDescription="An error occurred while connecting">
    <munit:execution>
        <mtf:test-connectivity config-ref="invalidConnectionWithErrorType"/>
    </munit:execution>
</munit:test>
----



== See Also

