= Java EE Libraries

In the first Mule runtime version that exclusively supports Java 17 (Mule 4.9.0), Java EE libraries will be removed from connectors. Mule 4.6.0 through Mule 4.9.0 will continue to export Java EE libraries as part of the Container API only when Mule runtime runs on Java 8 or Java 11 to ensure backward compatibility. However, if Mule runtime runs on Java 17 or higher, the Java EE libraries will be removed from connectors, so you will have to include the Java EE libraries manually. For connectors that support multiple Java versions, such as Java 11 and Java 17, the Java EE libraries must match the versions included in Mule runtime. 

Because Mule 4.6.x exposes Java EE libraries differently than earlier Mule versions, you must add the BOM dependency to your connector and, if applicable, exclude the provided conflicting library. You can also add the libraries in the BOM dependency separately.

[source,java,linenums]
----
<muleJavaEeBomVersion>4.6.0-20231025</muleJavaEeBomVersion>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.mule</groupId>
        <artifactId>mule-javaee-runtime-bom</artifactId>
        <version>${muleJavaEeBomVersion}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
----

== See Also 

* xref:general::customer-connector-upgrade.adoc[]
* xref:general::partner-connector-upgrade.adoc[]
* xref:general::java-support.adoc[]