= Troubleshoot SDK Components and Operations - Mule 4

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, sdk, known issue, bug, error, limitations

This section describes known issues or limitations around the Java SDK for Mule 4.

==  Error: cannot find org.mule.sdk.api classes

When using the 1.4.0 version of the module's parent pom:
[source,xml,linenums]
----
<parent>
  <groupId>org.mule.extensions</groupId>
  <artifactId>mule-modules-parent</artifactId>
  <version>1.4.0</version>
</parent>
----
you can encounter errors during compilation like 'Cannot access *XYZ* class file: *XYZ* not found' or  'Cannot find symbol: method someMethod() location: variable someVar of type *XYZ*' where *XYZ* is some class from the *org.mule.sdk.api* package.
For example:
----
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project : Compilation failure:

cannot access org.mule.sdk.api.runtime.streaming.StreamingHelper
[ERROR] class file for org.mule.sdk.api.runtime.streaming.StreamingHelper not found

cannot find symbol
[ERROR]   symbol:   method resolveCursors(java.util.HashMap<java.lang.String,java.lang.Object>,boolean)
[ERROR]   location: variable streamingHelper of type org.mule.runtime.extension.api.runtime.streaming.StreamingHelper
----
To solve this issue you must add the mule-sdk-api dependency to the pom.xml:
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.sdk</groupId>
    <artifactId>mule-sdk-api</artifactId>
    <version>0.4.0</version>
</dependency>
----
CAUTION: Unless you need new functionality from the new org.mule.sdk.api package, remember to keep using the annotations and classes from *org.mule.runtime.extension.api*. However if you do need any of the new annotations from the org.mule.sdk.api package, you must only use those classes that are annotated with `@MinMuleVersion("4.4")`.