= Parameterization
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Use a parameterized suite to run the same tests with different inputs. For more information, refer to xref:munit::munit-parameterized-suite.adoc[MUnit Parameterized Test Suite].

== Configuration Parameterization Example

The following example shows a test suite with two parameterizations, each pointing to a different configuration:

[source, java, linenums]
----
public Integer withConfig(@Config ExampleConfig config) {
    return config.getValue();
}
----

You can test different configurations as follows:

[source, xml, linenums]
----
<munit:config name="parameterized-configs-test">
    <munit:parameterizations>
        <munit:parameterization name="config1">
            <munit:parameters>
                <munit:parameter propertyName="config" value="config1"/>
                <munit:parameter propertyName="expected" value="1"/>
            </munit:parameters>
        </munit:parameterization>
        <munit:parameterization name="config2">
            <munit:parameters>
                <munit:parameter propertyName="config" value="config2"/>
                <munit:parameter propertyName="expected" value="2"/>
            </munit:parameters>
        </munit:parameterization>
    </munit:parameterizations>
</munit:config>

<test-connector:config name="config1" value="1"/>
<test-connector:config name="config2" value="2"/>

<munit:test name="parameterizedConfigsTest">
    <munit:execution>
        <test-connector:with-config config-ref="${config}" />
    </munit:execution>
    <munit:validation>
        <munit-tools:assert-equals actual="#[payload]" expected="#[${expected}]"/>
    </munit:validation>
</munit:test>
----

== Input Data Parameterization Example

Suppose you want to execute one operation but with different inputs, and each input has different expected outputs. For example, testing an operation that replaces one string input with another. Your operation uses the following syntax:

[source, java, linenums]
----
public String replace(String input, String toReplace, String replacement) {
    return input.replace(toReplace, replacement);
}
----

Your test for several different inputs for one operation looks like this:

[source, xml, linenums]
----
<munit:config name="parameterized-inputs-test">
    <munit:parameterizations>
        <munit:parameterization name="singleCharacter">
            <munit:parameters>
                <munit:parameter propertyName="input" value="foo"/>
                <munit:parameter propertyName="toReplace" value="o"/>
                <munit:parameter propertyName="replacement" value="e"/>
                <munit:parameter propertyName="expected" value="fee"/>
            </munit:parameters>
        </munit:parameterization>
        <munit:parameterization name="multipleCharacter">
            <munit:parameters>
                <munit:parameter propertyName="input" value="example"/>
                <munit:parameter propertyName="toReplace" value="ple"/>
                <munit:parameter propertyName="replacement" value="ination"/>
                <munit:parameter propertyName="expected" value="examination"/>
            </munit:parameters>
        </munit:parameterization>
    </munit:parameterizations>
</munit:config>

<munit:test name="parameterizedInputsTest">
    <munit:execution>
        <test-connector:replace input="${input}" toReplace="${toReplace}" replacement="${replacement}" />
    </munit:execution>
    <munit:validation>
        <munit-tools:assert-equals actual="#[payload]" expected="${expected}"/>
    </munit:validation>
</munit:test>
----




