= Using Test classes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When developing test cases, you may want to use Java classes located in `src/test/java`.
Java classes can be used through the java module or through DW.

For the following example, we will assume that our class is located in `src/test/java/com/example/MyUtilClass.java`

.MyUtilClass
[source, java, linenums]
----
package com.example.test;

public class Helper {

  public static long getCurrentMillis() {
    return System.currentTimeMillis();
  }

}
----

== Using DataWeave

To invoke static methods using DataWeave you must append the `java!` prefix to the package name of the class.

.Using a class in DataWeave
[source, xml, linenums]
----
<munit:test name="usingJavaInDW">
    <munit:behavior>
        <set-variable variableName="number" value="#[java!com::example::test::Helper::currentMillis()]" />
    </munit:behavior>
    <munit:execution>
        <test-connector:execute number="#[vars.number]"/>
    </munit:execution>
</munit:test>
----

== Using the Java Module

Make sure the java module is your project:

.Java Module dependency
[source, xml, linenums]
----
<dependency>
    <groupId>org.mule.module</groupId>
    <artifactId>mule-java-module</artifactId>
    <version>${javaModule.version}</version>
    <classifier>mule-plugin</classifier>
    <scope>test</scope>
</dependency>
----

Then you can use any of the Java Module's operations. In this case, we want to invoke a static method of a class:

.Using a class with the Java Module
[source, xml, linenums]
----
<munit:test name="usingJavaInDW">
    <munit:behavior>
        <set-variable variableName="number" value="#[java!com::example::test::Helper::currentMillis()]" />
    </munit:behavior>
    <munit:execution>
        <test-connector:execute number="#[vars.number]"/>
    </munit:execution>
</munit:test>
----

CAUTION: The MUnit Extensions Maven Plugin will automatically export any test packages and test resources located in your
project. In case your Module is already exporting a class located in `src/main/java`, then any test classes with the same package
located in `src/test/java` won't be able to be exported since there would be a conflict. In this case, you just change the test
classes package to a different one.




