= MTF Tools
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

MTF Tools is an extension with useful operations to test your module.

== Queue operations

Allows you to manage temporary queues during your test runs.
All queues will be `emptied as soon as the test ends`.

=== Queue

Adds the value to the queue. If not specified, the value is taken from the `payload`.

[source,xml,linenums]
----
<mtf:queue>
    <mtf:value>#[1]</mtf:value>
</mtf:queue>
----

You can specify the queue's name to which the value should be added. If not specified, the default queue will be used.

[source,xml,linenums]
----
<mtf:queue queueName="CUSTOM_QUEUE_1">
    <mtf:value>#[1]</mtf:value>
</mtf:queue>
----

=== Dequeue
Removes the last element of the queue, if the queue is empty, it waits until an element
is queued.

[source,xml,linenums]
----
<mtf:dequeue/>
----

You can specify a timeout when waiting for an element to be queued:

[source,xml,linenums]
----
<mtf:dequeue timeout="1000" timeoutUnit="SECONDS"/>
----

Like the queue operation, you can specify the queue's name from which to dequeue.
If not specified, the default queue will be used.

[source,xml,linenums]
----
<mtf:dequeue queueName="CUSTOM_QUEUE_1"/>
----


== See Also

* xref:2.2@munit::storage-processors.adoc[Storage Event Processors]