= Metadata Testing Examples
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following examples provide the basic test structure for testing the metadata defined for your Module. If you are not
familiarized with how to define metadata, you can read the following xref:metadata.adoc[page] and how Metadata tests work
in this other xref:metadata-testing.adoc[page].


Your Module can define the following metadata:

.Operation with Metadata
[source, java, linenums]
----
@OutputResolver(output = ExampleOutputResolver.class)
public Object withMetadata(@MetadataKeyId(ExampleKeysResolver.class) String param) {
    return null;
}
----

.TypeKeysResolver
[source, java, linenums]
----
public class ExampleKeysResolver implements TypeKeysResolver {

  @Override
  public Set<MetadataKey> getKeys(MetadataContext metadataContext) {
    Set<MetadataKey> metadataKeys = new HashSet<>();
    metadataKeys.add(newKey("firstKey").withDisplayName("First Key").build());
    metadataKeys.add(newKey("secondKey").withDisplayName("Second Key").build());
    return metadataKeys;
  }

  @Override
  public String getCategoryName() {
    return "ExampleCategory";
  }

}
----

.OutputResolver
[source, java, linenums]
----
public class ExampleOutputResolver implements OutputTypeResolver<String> {

  @Override
  public String getResolverName() {
    return "exampleResolver";
  }

  @Override
  public MetadataType getOutputType(MetadataContext context, String param) throws MetadataResolvingException {
    if (param == null || param.isEmpty()) {
      throw new MetadataResolvingException("No metadata available for an empty param", FailureCode.INVALID_METADATA_KEY);
    }
    ObjectTypeBuilder objectType = context.getTypeBuilder().objectType();
    objectType.addField().key("name").value().stringType();
    objectType.addField().key("age").value().numberType();
    return objectType.build();
  }

  @Override
  public String getCategoryName() {
    return "ExampleCategory";
  }
}
----

CAUTION: Implementations provided in the examples have fixed values to cover simplify the code.
The proper way to obtain metadata, should be through external services.

== Validating Metadata Keys

In the following example, we validate that the keys have the proper Display names:

.Tooling test to validate metadata keys
[source, xml, linenums]
----
<mtf:tooling-test name="keysTest">
    <mtf:get-metadata-keys>
        <test-connector:with-metadata />
    </mtf:get-metadata-keys>
    <mtf:validation>
        <munit-tools:assert-equals actual="#[payload.firstKey.displayName]" expected="#['First Key']"/>
        <munit-tools:assert-equals actual="#[payload.secondKey.displayName]" expected="#['Second Key']"/>
    </mtf:validation>
</mtf:tooling-test>
----

== Validating a Metadata Type

Apart from defining the keys for the operation parameter, the output metadata attached to those keys is defined.
In the following example, the test validates that Metadata Type returned by the operation:

.Tooling test to validate output metadata type of an operation
[source, xml, linenums]
----
<mtf:tooling-test name="outputMetadataTest">
    <mtf:get-output-metadata>
        <test-connector:with-metadata param="aValue"/>
    </mtf:get-output-metadata>
    <mtf:validation>
        <munit-tools:assert-equals actual="#[payload.format]" expected="#['java']"/>
        <munit-tools:assert-equals actual="#[payload.fields[0].key.name]" expected="#['name']"/>
        <munit-tools:assert-equals actual="#[payload.fields[0].model.'type']" expected="#['String']"/>
        <munit-tools:assert-equals actual="#[payload.fields[1].key.name]" expected="#['age']"/>
        <munit-tools:assert-equals actual="#[payload.fields[1].model.'type']" expected="#['Number']"/>
    </mtf:validation>
</mtf:tooling-test>
----

== Expecting a failure

In the case shown above a `MetadataResolvingException` is thrown when the parameter is null or empty.
In the following example, the test validates that the proper failure code and message are thrown when the parameter is invalid:

.Tooling test to validate metadata failures
[source, xml, linenums]
----
<mtf:tooling-test name="failureTest"
                  expectFailureMessage="No metadata available for an empty param"
                  expectFailureCode="INVALID_METADATA_KEY">
    <mtf:get-output-metadata>
        <test-connector:with-metadata param=""/>
    </mtf:get-output-metadata>
</mtf:tooling-test>
----






