= Operating the MUnit Extensions Maven Plugin
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Learn how to run your tests by using the MUnit Extensions Maven plugin.

== Run MUnit Tests for a Module Project

To run MUnit tests for your module:

[source,console]
----
mvn clean verify
----

== Run a Specific MUnit Test Suite

You can instruct the MUnit Extensions Maven plugin to run tests that belong only to a specific test suite by using the `munit.test` property:

[source,console]
----
mvn clean verify -Dmunit.test=<regex-test-suite>
----

The `munit.test` property accepts regular Java expressions applied to the name of the MUnit test suite file. The path is relative to `src/test/munit`.

For example:

[source,console]
----
mvn clean verify -Dmunit.test=.*my-test.*
----

You can leverage this feature by adding naming conventions to your MUnit test suites.

== Run Specific MUnit Tests

In the same way that you instruct MUnit to run one test suite, you can also instruct MUnit to run a specific test inside that test suite. To do so, use the `munit.test` property, followed by `#` and the test name:

[source,console]
----
mvn clean verify -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

The test also accepts regular expressions applied to the `name` attribute:

For example:

[source,console]
----
mvn clean verify -Dmunit.test=.*my-test.*#.*test-scenario-1.*
----

The MUnit Extensions Maven plugin flags tests inside the MUnit test suite as *ignored* if they don't match the regular expression. 

== Run Tests Using a Specific Tag

You can choose to run only the tests that you grouped under one specific tag:

[source,console]
----
mvn clean verify -Dmunit.tags=<munit-tag>
----

For more information about how to tag your tests, refer to xref:munit::munit-test-concept.adoc#test-tag-attribute[].

== Skip All Tests

When building your module, you can prevent a test from running by using the `skipTests` parameter:

[source,console]
----
mvn clean verify -DskipTests
----

== Debug Tests

When testing your module, you can debug your code. MUnit leverages Java remote debugging, so use the `munit.debug` parameter to debug your tests:

[source,console]
----
mvn clean verify -Dmunit.debug
----

The default debugger listens on port 5005. You can override the debugger JVM argument line by specifying it as the value of the property:

[source,console]
----
mvn clean verify -Dmunit.debug="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8002"
----

== See Also

* xref:munit::munit-showing-results.adoc[]
* xref:munit-extensions-maven-plugin-configuration.adoc[]
