= Configuring the MUnit Extensions Maven Plugin
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The MUnit Extensions Maven plugin provides testing capabilities for extension development. Learn how to configure the MUnit Extensions Maven plugin to test your modules. 

== Specify Additional Argument Lines

Because you run the tests in a new JVM, you can specify additional argument lines to the JVM. Specify each argument in a separate `argLine`.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <argLines>
          <argLine>-XX:MaxPermSize=512m</argLine>
          <argLine>-Xmx1024m</argLine>
      </argLines>
      ...
    </configuration>
  </plugin>
</plugins>
----

== Enable Runtime Discovery

Runtime discovery looks for all Mule runtime versions published on Nexus to run
against your tests.

To enable runtime discovery, add the following configuration to the MUnit Extensions Maven plugin:

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <runtimeConfiguration>
          <discoverRuntimes>
              <product>CE</product> //<1>
          </discoverRuntimes>
      </runtimeConfiguration>
      ...
    </configuration>
  </plugin>
</plugins>
----
[calloutlist]
.. This enables the runtime discovery feature for all released CE runtimes.

From the command line, the property is `discoverRuntimes.product`.

NOTE: The `product` can be CE (Community Edition), EE (Enterprise Edition), or ALL (both CE and EE).

=== Include Snapshots

To include snapshot versions of Mule runtime, add the following line to the runtime configuration:

[source,xml,linenums]
----
<runtimeConfiguration>
    <discoverRuntimes>
        <product>CE</product>
        <includeSnapshots>true</includeSnapshots>
    </discoverRuntimes>
</runtimeConfiguration>
----

From the command line, the property is `discoverRuntimes.includeSnapshots`. The default value is `false`.

=== Discover Only the Latest Patches

To discover only the latest patch versions of Mule runtime, add the following line to the runtime configuration:

[source,xml,linenums]
----
<runtimeConfiguration>
    <discoverRuntimes>
        <product>CE</product>
        <latestPatches>true</latestPatches>
    </discoverRuntimes>
</runtimeConfiguration>
----

From the command line, the property is `discoverRuntimes.latestPatches`. The default value is `true`.

=== Discover Since a Minimum Version

By default, runtime discovery searches for all Mule runtime versions since the `minMuleVersion` of the module. To change this minimum version, add the following line to the runtime configuration:

[source,xml,linenums]
----
<runtimeConfiguration>
    <discoverRuntimes>
        <product>CE</product>
        <minMuleVersion>4.1.2</minMuleVersion>
    </discoverRuntimes>
</runtimeConfiguration>
----

From the command line, the property is `discoverRuntimes.minMuleVersion`. The default value is the `minMuleVersion` of the module.

=== Run Against Additional Runtimes

By default, the MUnit Extensions Maven plugin runs against the `minMuleVersion` and the required product of the module. To specify additional runtimes to run against, add the following lines to the runtime configuration:

[source,xml,linenums]
----
<runtimeConfiguration>
    <additionalRuntimes>
        <additionalRuntime>MULE_EE:4.1.2</additionalRuntime>
        <additionalRuntime>MULE:4.1.1</additionalRuntime>
    </additionalRuntimes>
</runtimeConfiguration>
----

From the command line, the property is `additionalRuntimes`.

=== Skip Runtime Discovery

To skip runtime discovery, add the following line to the runtime configuration:

[source,xml,linenums]
----
<runtimeConfiguration>
    <discoverRuntimes>
        <product>CE</product>
        <skip>true</skip>
    </discoverRuntimes>
</runtimeConfiguration>
----

From the command line, the property is `discoverRuntimes.skip`. The default value is `false`.

== Use Dynamic Ports

[IMPORTANT]
MUnit 2.2 and later introduces the `dynamic-port` global element, which you can use to define dynamic ports at the MUnit suite level. +
Use this element instead of the plugin configuration described below to set the dynamic port both from Maven and Studio. +
For more information about how to configure this element, refer to xref:munit::dynamic-ports.adoc[Dynamic Ports].

When testing a module in a continuous integration (CI) environment, you might encounter the following scenario:

`Your test tries to open a specific port. The port is already in use. The test fails with a port binding exception.`

To solve this, use the dynamic ports built-in feature in the MUnit Extensions Maven plugin to have your test use a free port. Dynamic ports instruct the MUnit Extensions Maven plugin to look for unbound ports and reserves them before running the tests over the module. Each port selected is placed in a system property under the name indicated in the configuration. The test can acquire the port number through the use of placeholders afterward.

TIP: The ports to select by the MUnit Extensions Maven plugin are taken from the following range: `[40000,50000)`.

[CAUTION]
--
The dynamic ports feature is available only as part of the MUnit Extensions Maven Plugin. +
You cannot expect this feature to work when running tests from inside Anypoint Studio.
--

=== Enable Dynamic Ports

To enable the dynamic ports feature, add the following code to the `configuration` section of the MUnit Extensions Maven plugin:

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
    ...
    <dynamicPorts>
      <dynamicPort>a.dynamic.port</dynamicPort>
    </dynamicPorts>
    ...
    </configuration>
  </plugin>
</plugins>
----

If you have the `${http.port}` placeholder in your test, the configuration looks like this:

[source,xml,linenums]
----
<dynamicPorts>
  <dynamicPort>http.port</dynamicPort>
</dynamicPorts>
----

== Disable Surefire Reports

MUnit has built-in support for Surefire. No additional configuration is needed but it can be disabled if not needed.

[source,xml,linenums]
----
<enableSurefireReports>false</enableSurefireReports>
----

The reports can be found under `${project.build.directory}/surefire-reports`.

The default value is `true`.

== Run Specific Tests

To run specific tests, add a line for the specific test:

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-extensions-maven-plugin</artifactId>
      <configuration>
      ...
      <munitTest>example-MunitTest-suite.xml</munitTest>
      ...
    </configuration>
  </plugin>
</plugins>
----

== Run Tests With Specific Tags

To run tests with specific tags, add a line for the test with the specific tag:

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-extensions-maven-plugin</artifactId>
      <configuration>
      ...
      <munitTags>exampleMunitTag</munitTags>
      ...
    </configuration>
  </plugin>
</plugins>
----

You can specify more than one tag by separating them with a comma.

== Skip MUnit Tests

To skip MUnit tests, add a line to skip MUnit tests:

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-extensions-maven-plugin</artifactId>
      <configuration>
      ...
      <skipMunitTests>True</skipMunitTests>
      ...
    </configuration>
  </plugin>
</plugins>
----

== Skip Tests After One Suite Fails

To skip the rest of the tests if one test suite fails, add a line to skip after failure:

[source,xml,linenums]
----
<plugins>
  <plugin>
      <groupId>com.mulesoft.munit.tools</groupId>
      <artifactId>munit-extensions-maven-plugin</artifactId>
      <configuration>
      ...
      <skipAfterFailure>true</skipAfterFailure>
      ...
    </configuration>
  </plugin>
</plugins>
----

The default value is `false`.

== Specify the Runtime Version

MUnit allows you to specify the runtime version in which your module being tested will run.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <runtimeVersion>1.2.3</runtimeVersion>
      ...
    </configuration>
  </plugin>
</plugins>
----

WARNING: If this option is set, runtime discovery and additionalRuntimes won't take effect.

== To Specify The Runtime Product

MUnit allows you to specify the type of runtime in which your module being tested will run. +
The two possible values are MULE for community edition, and MULE_EE for Enterprise Edition.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <runtimeProduct>MULE</runtimeProduct>
      ...
    </configuration>
  </plugin>
</plugins>
----

WARNING: If this option is set, runtime discovery and additionalRuntimes won't take effect.

== To Specify The JVM

MUnit allows you to specify the jvm (or the java executable) in which your module being tested will run.
The property should be populated with the path to the executable.

[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <jvm>/path/to/jdk/bin/java</jvm>
      ...
    </configuration>
  </plugin>
</plugins>
----

From the command line, the property is `-Dmunit.jvm`

== Environment Variables

To set additional environment variables during the test run, you can specify
them with the respective key and value.

.Additional Environment Variables
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <environmentVariables>
        <MY_ENV>exampleValue</MY_ENV>
        <MY_OTHER_ENV>val2</MY_OTHER_ENV>
      </environmentVariables>
      ...
    </configuration>
  </plugin>
</plugins>
----

Environment variables can be used to replace placeholders such as `${MY_ENV}`
(using the example above).

== Redirect Test Output to File

When running several tests, the build output can get very complex to read. You may want
to redirect the output of each Test suite to a file. This way what remains in the build
output will be the test results and to check the standard output of each test suite you can find it
in its respective file.

These files will be located in the `testOutputDirectory` folder following this naming convention:
`munit.${suiteName}-output.txt`, where the `suiteName` represents the name of the XML file relative to the
MUnit test folder.

The test run output that doesn't belong to a particular suite won't be printed to keep the build output clean, but it can be enabled by running maven in _debug_ mode.

.Redirect test output to file
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <redirectTestOutputToFile>true</redirectTestOutputToFile>
      ...
    </configuration>
  </plugin>
</plugins>
----

By default, it is set to `false`

== System Properties Variables

You may wish to define specific system variables needed for your MUnit test to run successfully. The example below shows how you can send them.

.Setting system property variables
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <systemPropertyVariables>
        <my.property.key>my.property.value</my.property.key>
      </systemPropertyVariables>
      ...
    </configuration>
  </plugin>
</plugins>
----

[TIP]
====
Depending on the execution context, the system properties values may vary. When referencing these properties, it is a good practice to override their value to enforce test reproducibility.

You can do so using the ­`-D` argument when running MUnit with Maven. +
Variables passed with the `-D` argument take full priority over any other property.

For example:

`-Dmy.property.key=my.property.another.value`
====

== Test Output Directory

You may want to choose the location where the test output files will be created.
The path specified can be absolute or written as a maven placeholder.

.Test output directory with absolute path
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <testOutputDirectory>/my/absolute/path</testOutputDirectory>
      ...
    </configuration>
  </plugin>
</plugins>
----

.Test output directory using maven placeholders
[source,xml,linenums]
----
<testOutputDirectory>${project.build.directory}/my/output/folder</testOutputDirectory>
----

By default, the files will be created in `${project.build.directory}/munit-reports/output/`.

== Shared Libraries

When requiring external libraries as explained xref:external-libs[here], you need to specify
these libraries as `sharedLibraries` (apart from having the corresponding dependencies in the project).

For example if you defined the following annotation in your module:

.External Library
[source,java,linenums]
----
@ExternalLib(name = "My External Library",
requiredClassName = "com.example.MyClass",
coordinates = "com.example:my-external-library:1.2.3")
----

You should configure the plugin in the following way:

.Shared Libraries
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
      <sharedLibraries>
          <sharedLibrary>
              <groupId>com.example</groupId>
              <artifactId>my-external-library</artifactId>
          </sharedLibrary>
      </sharedLibraries>
      ...
    </configuration>
  </plugin>
</plugins>
----

== Importing External Suites and Resources

If you want to reuse suite files across different modules and they are present in an external artifact, the plugin
allows you to include them in the run (as if they were present in the `src/test/munit` and `src/test/resources` folders).

Make sure that the dependencies are in the plugin's classpath adding them as dependencies of the plugin.

You should configure the plugin in the following way:

.External suites and resources
[source,xml,linenums]
----
<plugins>
  <plugin>
    <groupId>com.mulesoft.munit.tools</groupId>
    <artifactId>munit-extensions-maven-plugin</artifactId>
    <configuration>
      ...
        <externalSuites>
            <externalSuite>suite1.xml</externalSuite>
            <externalSuite>suite2.xml</externalSuite>
        </externalSuites>
        <externalResources>
            <externalResource>example.json</externalResource>
        </externalResources>
      ...
    </configuration>
    <dependencies>
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>my-dependency</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
  </plugin>
</plugins>
----

If any of the suite files or resources are not present in the classpath, the plugin fails.


== See Also

* xref:munit-extensions-maven-plugin.adoc[]
