= Getting Started
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To create a connector using REST SDK:
* Use a CLI command to scaffold a Connector Descriptor for an API Spec.
* Use a CLI command to create a Connector from an API Spec and a Connector Descriptor.
* Perform some example modifications to the Connector Descriptor for
tailoring the generated connector.
* Build the connector using Maven.
* Publish the connector to Anypoint Exchange.

== Prerequisites

* Download REST SDK: https://repository-master.mulesoft.org/nexus/service/local/repositories/releases/content/com/mulesoft/connectors/rest-connect-cli/1.0.0-RC2/rest-connect-cli-1.0.0-RC2-jar-with-dependencies.jar[rest-connect-cli-1.0.0-RC2.jar]
* Install Java SDK
* Apache Maven

== Scaffold the Connector Descriptor

To scaffold the Connector Descriptor, you must run the
*create-descriptor* command:

[cols="",]
|===
|java -jar
$PATH_TO_JAR/rest-connect-cli-1.0.0-RC2-jar-with-dependencies.jar
create-descriptor -apiSpec $PATH_TO_SPEC/api.raml -outputDir $OUTPUT
|===

The create-descriptor command uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes |The relative path to the API spec for which you want to
create a Connector Descriptor. |-

|specFormat |No a|
The format of the API spec.

Allowed values are RAML, JsonOAS, and YamlOAS

|RAML

|parser |No a|
The parser you want to use to parse the API spec.

Allowed values are AMF and RAMLParser.

You should not use RAMLParser.

|AMF

|outputDir |No a|
The path where the Connector Descriptor is placed.

The generated file is named output.yaml and located in the specified
folder.

|Current directory

|mode |No |The mode in which you want the connector descriptor to be
generated. Allowed values are MINIMAL and VERBOSE. |MINIMAL

|skipValidation |No |Allows you to skip the validation step for the API
specification. Users should not skip the validations as the successful
parsing of an invalid API spec is not guaranteed. Users who skip
validation might experience issues generating the connector descriptor
and the connector. |FALSE
|===

== Create Connector

After you have modified the Connector Descriptor, you can generate the
connector using the *create-connector* command:

[cols="",]
|===
|java -jar
$PATH_TO_JAR/rest-connect-cli-1.0.0-RC1-jar-with-dependencies.jar
create-connector -apiSpec $PATH_TO_SPEC/api.raml -apiDesc
$PATH_TO_DESCRIPTOR/descriptor.yaml -outputDir $OUTPUT
|===

The create-connector command uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes |The relative path to the API spec for which you want to
create a Connector. |-

|apiDesc |Yes |The relative path to the Connector Descriptor that you
created to customize the API spec. |-

|specFormat |No a|
The format of the API spec.

Allowed values are RAML, JsonOAS, and YamlOAS

|RAML

|parser |No a|
The parser you want to use to parse the API spec.

Allowed values are AMF and RAMLParser.

You should not use RAMLParser.

|AMF

|outputDir |No a|
The path where the connector resides.

The generated file is named output.yaml and is located in the specified
folder.

|Current directory

|skipValidation |No |Allows you to skip the validation step for the API
spec. Users should not skip the validations as the successful parsing of
an invalid API spec is not guaranteed. Users who skip validation might
experience issues generating the connector descriptor and the connector.
|FALSE
|===

== What's Next?

xref:customize-connector-descriptor.adoc
