= Security Scheme
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Ignore a Security Scheme

If your API spec defines a security scheme that you don’t want to be
present in the generated connector, you can use the `ignored` property
in the `security` node of your Connector Descriptor.

[cols="",]
|===
a|
*security:*

*passThrough*:

*ignored*: true

|===

In this case, the API spec declares a security scheme named `passThrough`.
The example uses the ignored annotation, so it does not get generated in
the Connector Descriptor.

== Set a Security Scheme Parameter Friendly Name

You can set friendly names for security scheme parameters using the
`displayName` annotation in the security scheme node of the Connector
Descriptor. You can use the `ignored` property in the `security` node of
your Connector Descriptor.

[cols="",]
|===
a|
*security:*

*passThrough:*

*headers:*

*passThroughHeader:*

*friendlyName*: 'Auth Header'

|===

In this case, the API spec defines the security scheme name `passThrough`
which has a parameter named `passThroughHeader` defined. The `friendlyName`
property is assigned the value ‘Auth Header’.
