= Tracing features

The `mule-sdk-compatibility-api` dependency in https://docs.mulesoft.com/mule-sdk/latest[Mule SDK] allows SDK developed components to contribute to the telemetry data generated by Mule runtime engine.
This dependency enables you to define the main span name of operations and sources. Additionally, you can enrich the span by adding custom attributes or even defining the span kind in terms of OpenTelemetry.

It also allows the implementation of trace context propagation, fully integrating mule to a distributed tracing system.

[[setup]]
== Install the Dependency

Ensure that the `mule-sdk-compatibility-api` dependency is included in your generated https://docs.mulesoft.com/mule-sdk/latest/getting-started#setup_ide[Mule SDK project]:

[source,xml,linenums]
----
<dependencies>
  ...
  <dependency>
        <groupId>org.mule.sdk</groupId>
        <artifactId>mule-sdk-compatibility-api</artifactId>
        <version>1.0.0</version>
  </dependency>
  ...
</dependencies>
----

Including this dependency enables the injection of a forward compatibility helper that provides backward compatible feature access when the supported MinMuleVersion is 4.4.0, meaning you can release the connector as a minor semver version.

== Retrieve the Distributed Trace Context Manager

In your operation or source class, you can inject the forward compatibility helper to obtain the distributed trace context manager.

[source,java,linenums]
----
@Inject
private java.util.Optional<ForwardCompatibilityHelper> forwardCompatibilityHelper;
----
This helper provides access to features from the `mule-sdk-compatibility-api` dependency even when they are not supported by Mule. This ensures that using these features in the future does not impact the connector.

== Example: Customizing an operation span

Suppose you have the following module:

[source,java,linenums]
----
@Extension(name = "Foo")
@Operations(FooOperations.class)
public class FooModule {

    @Parameter
    private String fooModuleParameter;

    public String getFooModuleParameter() {
        return fooModuleParameter;
    }
}
----

The operation class can be this:

[source,java,linenums]
----
public class FooOperations {

    @Inject
    private java.util.Optional<ForwardCompatibilityHelper> forwardCompatibilityHelper;

    public String foo(@Config FooModule config,
                  CorrelationInfo correlationInfo) {


        DistributedTraceContextManager distributedTraceContextManager = fcHelper.getDistributedTraceContextManager(correlationInfo);

        // Override the current span name.
        distributedTraceContextManager.setCurrentSpanName("fooOperation");

        // Add an additional attribute to the span.
        distributedTraceContextManager.addCurrentSpanAttribute("attributeKey", "attributeValue");
        return "OK";
    }
}
----

== Example: Customizing a source span

You can retrieve the distributed trace context manager to interact with the current span corresponding to the source.

Using the source in https://docs.mulesoft.com/mule-sdk/latest/sources-push-message[Pushing Messages to a Flow from a Message Source], the source class can be this:

[source,java,linenums]
----
public class HttpListener extends Source<InputStream, HttpRequestAttributes> {

    @Inject
    private java.util.Optional<ForwardCompatibilityHelper> forwardCompatibilityHelper;

    @Override
    public void onStart(SourceCallback<InputStream, HttpRequestAttributes> sourceCallback) throws MuleException {
        httpServer = serverProvider.connect();

        server.listen(path).onRequest(request -> {

            SourceCallbackContext context = sourceCallback.createContext();
            if (forwardCompatibilityHelper.isPresent()) {
                DistributedTraceContextManager distributedTraceContextManager =
                forwardCompatibilityHelper.get().getDistributedTraceContextManager(context);

                // No we can interact with the current span.
                // Override the current span name.
                distributedTraceContextManager.setCurrentSpanName("http:special-source");

                // Add an additional attribute to the span.
                distributedTraceContextManager.addCurrentSpanAttribute("attributeKey", "attributeValue");

            }

            Result<InputStream, HttpRequestAttributes> result = requestToResult(request, context);

            sourceCallback.handle(result);
        });
    }
}
----

== Tracing Context Propagation

Sources and connectors play a special role in both mule and distributed tracing.

In the mule paradigm, the source is the trigger of a flow but also the first span of its corresponding trace. That makes it responsible for handling the “distributed” part of distributed tracing: It needs to consider that the trace may be already generated and must be continued instead of generated from scratch.

The connector is on the opposite side of this paradigm: It needs to propagate the current trace for further continuation on systems that can even be external to mule (databases, non-mule APIs, message queues, etc).

The Mule runtime Java SDK supports the W3C trace context propagation standard, which defines a https://www.w3.org/TR/trace-context/#trace-context-http-headers-format[tracing context] consisting of a trace parent and a trace state.

[source,text]
----
traceparent: 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
tracestate: congo=t61rcWkgMzE
----

We can use the HTTP listener and the HTTP requesters as examples of the context propagation.

When the listener receives W3C trace context headers as part of the request, it must indicate where to retrieve the W3C trace context using the DistributedTraceContextManager:

[source,java,linenums]
----
public class HttpListener extends Source<InputStream, HttpRequestAttributes> {

    @Override
    public void onStart(SourceCallback<InputStream, HttpRequestAttributes> sourceCallback) throws MuleException {
        httpServer = serverProvider.connect();

        server.listen(path).onRequest(request -> {

            SourceCallbackContext context = sourceCallback.createContext();
            if (forwardCompatibilityHelper.isPresent()) {
                DistributedTraceContextManager distributedTraceContextManager =
                     forwardCompatibilityHelper.get().getDistributedTraceContextManager(context);
                // This defines the map where the W3C trace context key values are available for retrieval (an HTTP request in this case, so the HTTP headers are read).
                // The mule runtime will trace the flow execution as child spans of this provided trace context.
                distributedTraceContextManager.setRemoteTraceContextMap(request.getHeaders());
            }

            Result<InputStream, HttpRequestAttributes> result = requestToResult(request, context);

            sourceCallback.handle(result);
        });
    }
}
----

The requester must retrieve the W3C trace context of the current span in an operation using `getRemoteTraceContextMap` instead, and then propagate it:

[source,java,linenums]
----

public class HttpRequestOperations implements Initialisable, Disposable {

    @Inject
    private java.util.Optional<ForwardCompatibilityHelper> forwardCompatibilityHelper;

    public void request(HttpRequesterConfig config, CorrelationInfo correlationInfo) {
        HttpRequestBuilder builder = httpRequestCreator.createRequestBuilder(config);
        if (forwardCompatibilityHelper.isPresent()) {
            // This obtains the current trace context as a map, propagating it to the connected system (an HTTP endpoint in this case, so HTTP headers are set).
            forwardCompatibilityHelper.get().distributedTraceContextManager.getRemoteTraceContextMap().forEach(builder::addHeader);
        }
    }
}
----

== Distributed Trace Context API

The following table shows the distributed trace context manager methods:

|===
|Method | Parameter | Description
|`void setRemoteTraceContextMap(Map<String, String> contextMap)` |`contextMap` |The `Map<String, String>` representing the key-value pairs that store the information of the remote trace context.
|`void setCurrentSpanName(String name)` |`name` |The name of the current span.
|`Map<String, String> getRemoteTraceContextMap()` |  N/A  |Returns the context map corresponding to the remote trace context.
|`void addCurrentSpanAttribute(String key, String value)` a|
* `key`
* `value` a|
* The key for the span attribute.
* The value for the span attribute. `span.kind.override` as key overrides the span kind.
|`void addCurrentSpanAttributes(Map<String, String> attributes)` |`attributes` |A `Map<String, String>` representing the attributes to add to the current span. `span.kind.override` as key overrides the span kind.
|===

== See Also

* https://docs.mulesoft.com/mule-runtime/latest/otel-support[OpenTelemetry support in Mule Runtime]