= Customization Layer
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Composition is defined in a customization layer file, which is an
instance of an existing connector descriptor. When you create a connector using this file, the connector is versioned and released
separately from the base connector.

== Create a Customization Layer for Composer

This composition feature is a part of the standard connector creation flow.
The only difference is that multiple connector descriptors can be specified in
the create connector command.

The following example shows what the create connector command looks like:
----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createConnector -DapiSpec=api.raml -Ddescriptor=connector-descriptor.yaml,customization-layer.yaml
----

The descriptors are used in the order they are specified. In this case,
the `connector-descriptor.yaml` is applied first, and is then overwritten by
the `customization-layer.yaml`.

== Composing Descriptors

When composing standard connector descriptors, the properties declared in a
descriptor override those declared in previous (base) descriptors.

For example, if the connector name and description are set in the first (base) layer
and then the connector _name_ is overwritten in a second descriptor layer, the final generated connector will have the name of the second layer and the description of the first layer.
