= Customize the Connector's Connectivity Testing
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Configure and customize connectivity testing of the connector descriptor of the connector.

Connectivity testing enables the connector user to check whether a connection
against a server is valid in design time.

By default, the generated connectors and their connection providers do not include
a generated test connection method. REST SDK enables defining test connection
methods to the generated connection providers in the connector descriptor.

== Add a Test Connection Method

To add a test connection method, you must define a test connection method in
the `testConnection` property, which is located in the connector descriptor.

A test connection can be defined globally for all of the generated connections
or can be defined for a specific connection provider.

[source,yaml]
----
testConnection:
  path: my/path
  validStatusCodes:
     - 200
  responseValidation:
     validation:
        language: dw
        expression: "#[payload contains('string')]"

security:
  basic:
   testConnection:
     path: test/passtwo/fail
     method: post
     mediaType: application/json
     validStatusCodes: 210
     responseValidation:
       - validation:
           expression: "#[payload.userId != null]"
       - validation:
           expression: "#[payload.userId == 'lucas.giordano']"
         errorTemplate:
           expression: "#['userId (' ++ payload.userId ++ ') is expected to be lucas.giordano']"
----

This example shows both a global definition and a definition that is specific to a connection provider.

In cases where both test connections are defined, the one defined for the security scheme takes precedence.

In the `testConnection` property, you can define multiple settings for the test connection method you are generating:

[cols=",,",options="header",]
|===
|Property Name |Description |Default Value
a|
path

(Mandatory)

|This property enables defining the path where the connection validation
request is made. +
This can, for example, be a /health endpoint of the server API. +
If you are adding this property to a security scheme, this path must point to a secured endpoint, as this enables the user to validate that the credentials they are using in the connector configuration are valid. |-

|validStatusCodes |This property accepts a list of status codes that are
considered as a valid server response status code. The server response
for the connection validation request is validated against this list,
and if a status code is not included, the connection is considered invalid, and the
connector shows an error message specifying this. |200

|mediaType a|
The media type of the server response body.

REST SDK gets the media type from the Content-Type header, so you must use this property if the response does not have a content-type header or if you want to override it.

|-

|method |Defines the method to use when making the request to the testConnectionPath. |GET

|responseValidation |This property expects a list of TestConnectionResponseValidation**.** |-

|TestConnectionResponseValidation |Consists of a validation and an errorTemplate. |-

|validation +
(Mandatory if responseValidation is defined) a|
An expression used to validate the HTTP test connection request's response.

This expression must return `true` if the response is valid or `false` if the response is not valid.

REST SDK assigns the body and attributes of the server response to the payload and attributes' variables respectively.

|-

|errorTemplate a|
Enables defining a message that is shown to the user if the connection validation fails.

A default error describing that the validation expression failed appears if this expression is not defined.

|-
|===
