= Create a Connector
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

After scaffolding and modifying the connector descriptor, use a mojo to create a connector
from an API specification and a connector descriptor.

== Create the Connector

To generate the connector, run the `createConnector` mojo:

----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createConnector -DapiSpec=<PATH_TO_SPEC>/api.raml -Ddescriptor=<PATH_TO_DESCRIPTOR>/descriptor.yaml
----

* Where `<PATH_TO_SPEC>` is the location of your API specification.
* Where `<PATH_TO_DESCRIPTOR>` is the location of your connector descriptor.
* Where `<PLUGIN_VERSION>` is the version of the REST SDK plugin you want to use.
If you omit this parameter, the latest version is used.

The `createConnector` mojo uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes
|Relative path to the API specification for which to
create a connector. |-

|descriptor |Yes
|Relative paths to the connector descriptors used to customize the connector. Can be a single relative path to a connector descriptor or a comma-separated list of relative paths to connector descriptors.|-

|specFormat
|No
a|Format of the API specification. +


Allowed values are `RAML`, `JsonOAS`, `YamlOAS`, `JsonOAS3`, and `YamlOAS3`. +


For API specification formats that are not supported, use https://www.apimatic.io/transformer/[API Transformer] by APIMatic to transform the format into `RAML` or `OAS` to use the tooling provided by REST SDK.
|If not specified, REST SDK autodetects the format based on the file extension and content.

|outputDir
|No
a|Path in which the connector is located. +


The generated file is named `output.yaml` and is located in the specified
folder.
|Current directory


|skipValidation |No |Enables you to skip the validation step for an API
specification. Selecting `TRUE` might result in an invalid API specification or
issues generating the connector descriptor.

|`FALSE`


|dynamicMetadata
|No
|Creates backward compatible dynamic metadata for operations.
|`FALSE`

|===

== What's Next

Now that you've created a connector from an API specification and connector descriptor,
optionally proceed to xref:rest-sdk/customization-layer.adoc[Customization Layer]
to generate another layer of functionality. Otherwise, proceed to
xref:rest-sdk/customize-the-connector.adoc[Customize Your Connector] to start
modifying your connector.
