= Create a Connector
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

After scaffolding and modifying the connector descriptor, use a mojo to create a connector
from an API specification and a connector descriptor.

== Create the Connector

To generate the connector, run the `createConnector` mojo:

----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createConnector -DapiSpec=<PATH_TO_SPEC>/api.raml -Ddescriptor=<PATH_TO_DESCRIPTOR>/descriptor.yaml
----

* Where `<PATH_TO_SPEC>` is the location of your API spec.
* Where `<PATH_TO_DESCRIPTOR>` is the location of your descriptor.
* Where `<PLUGIN_VERSION>` is the version of the Rest SDK Plugin you want to use.
If you omit this parameter, the latest version is used.

The createConnector mojo uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes
|The relative path to the API spec for which you want to
create a connector. |-

|descriptor |Yes
|The relative paths to the connector descriptors that will be used to customize the connector. The value for this parameter can be a single relative path to a connector descriptor or a list of those, split with commas.|-

|specFormat
|No
a|The format of the API spec.

Allowed values are RAML, JsonOAS, YamlOAS, JsonOAS3, and YamlOAS3. For specFormats that are not supported, use https://www.apimatic.io/transformer/[API Transformer] by APIMatic to transform them into RAML or OAS to use the tooling provided by REST SDK.

|If not specified, it will autodetect the format based on the file extension and content.

|outputDir
|No
a|The path where the connector resides.

The generated file is named `output.yaml` and is located in the specified
folder.
|Current directory


|skipValidation
|No
|Allows you to skip the validation step for the API
spec. Users should not skip the validations as the successful parsing of
an invalid API spec is not guaranteed. Users who skip validation may
experience issues generating the connector.
|FALSE


|dynamicMetadata
|No
|Creates backwards compatible Dynamic Metadata for Operations.
|FALSE

|===
