= Configure Operations
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

== Data Expressions
Data Expressions are small semantic snippets that are used in several sections of the Connector Descriptor to describe actions as an HTTP Request or the execution of a script.

=== HTTP Request
Describes an HTTP Request against the API.

It consists on a path, the HTTP method and parameter bindings.

[cols=",,",options="header",]
|===
| Property | Required | Description
| path | Yes | The path where to make the HTTP request. Relative to the API base URI.
| method | Yes | The HTTP method to use in the request. The allowed values are: `get`, `post`, `put`, `patch`, `delete`, `head`, `options`.
| binding | No | Describes the parameters that will be sent in the request. Allows adding `uriParameter`, `queryParameter` and `header` bindings. Each of those lists can contain multiple parameter bindings.
|===

[source, yaml]
----
request:
  path: /channels
  method: get
  binding:
    queryParameter:
      kind:
        value: "#[parameter.channelType]"
      count:
        value: "#[10]"
----

==== HTTP Binding Context

The HTTP Request Data Expression will have access to the context where it is declared.

- If it is declared in an *Operation* context, it will have access to the `uriParameter`, `queryParameter` and `header` variables, containing the operation's uriParameters, queryParameters and headers respectively.

- If it is declared in a *Trigger*, it will have access to the `parameter` variable, containing all the declared trigger parameters.

- If it is declared in a *global resolver* definition -Such as a global sample data or value provider definition-, it will have access to the `parameter` variable, containing all the global resolver declared parameters.


=== Script
Describes the execution of a script.

[source, yaml]
----
script:
  language: "dataweave"
  expression: "#[payload.data[0]]"
----

[cols=",,",options="header",]
|===
| Property | Required | Description
| expression | Yes | The actual script expression.
| language | No | The expression language. Default: `dataweave`.
|===
