= Customize the Connector's Data Expressions
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Configure and customize data expressions of the connector descriptor of the connector.

Data expressions are semantic snippets used in the connector descriptor to describe
actions, such as an HTTP Request or an execution of a script.

== HTTP Request

An HTTP request data expression can describe an HTTP request against the API. The
HTTP request data expression consists of a path, the HTTP method, and parameter bindings.

[source, yaml]
----
request:
  path: /channels
  method: get
  binding:
    queryParameter:
      kind:
        value: "#[parameter.channelType]"
      count:
        value: "#[10]"
----

[cols=",,",options="header",]
|===
| Property | Required | Description
| path | Yes | The path that makes the HTTP request. Relative to the API base URI.
| method | Yes | The HTTP method used in the request. The allowed values are `get`, `post`, `put`, `patch`, `delete`, `head`, and `options`.
| binding | No | Describes the parameters that are sent in the request. The allowed values are `uriParameter`, `queryParameter`, and `header`. Each of these values can contain multiple parameter bindings.
|===


=== HTTP Binding Context

The HTTP request data expression has access to the context depending on where the HTTP request data expression is declared.

- If the HTTP request data expression is declared in an *operation*, it has access to the `uriParameter`, `queryParameter`, and `header` variables, which contains the operation's uriParameters, queryParameters, and headers.

- If the HTTP request data expression is declared in a *trigger*, it has access to the `parameter` variable, which contains all the declared trigger parameters.

- If the HTTP request data expression is declared in a *global resolver* definition, such as a global sample data or value provider definition, it has access to the `parameter` variable, which contains all the global resolver declared parameters.


== Script

A script data expression describes the execution of a script. The script data expression consists of an expression and a language.

[source, yaml]
----
script:
  language: "dataweave"
  expression: "#[payload.data[0]]"
----

[cols=",,",options="header",]
|===
| Property | Required | Description
| expression | Yes | The actual script expression.
| language | No | The expression language. The default is `dataweave`.
|===
