= Paginated Operations
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Neither OAS nor RAML provides a way to declare that an operation is
paginated.

You can use the Connector Descriptor to augment these specs and allow
pagination in the API operations.

REST SDK supports the following pagination strategies:

Offset based paging:: For APIs which do paging based on an offset query
parameter which requests results starting from result number N.

Marker-based paging:: For APIs which do paging based on a marker
query parameter which points to a position in the dataset to be
returned.

Page number:: For APIs which do paging based on a query param which
represents the page number to get.


== Pagination Configuration Parameters

For all paginations strategies, you must define name, type, and
parameters.

=== Name

The pagination name can be any string that you want to use to identify
the pagination through the Connector Descriptor. You must use the
pagination name when an operation is paged using this strategy.

=== Type

The type defines the behavior of the pagination strategy.

As indicated previously, there are 3 possible strategies: _offset_,
_marker_, and _pageNumber_.

=== Parameters

Each pagination endpoint has parameters that take a role in the
paginated operation. These vary depending on the pagination strategy.

==== Offset Pagination

For _offset_ pagination, the available parameters are:

offsetParamName:: Indicates the name of the query parameter that must
be passed to the API to indicate the initial position of the next page.

initialOffset:: The initial value the connector passes to the
previously indicated query parameter.

==== Marker Pagination

For _marker_ pagination, the available parameters are:

nextTokenParamName:: Indicates the name of the query parameter that
must be passed to the API to indicate where the next page starts.

nextToken:: This is a dataweave expression that the connector
uses to extract the next page token from the API response. This token is
then used to request the page that follows.

==== Page Number Pagination

For _pageNumber_ pagination, the available parameters are:

pageNumberParamName:: Indicates the name of the query parameter that
must be passed to the API to indicate the page number we want to get
from the server.

initialPageNumber:: The initial value the connector passes to the
previously indicated query parameter.

The _pagingResponse_ is common to all the pagination
strategies; it provides the expression used to extract the item data
from the response.

== Payload Dataweave Expression

Some APIs return the pages directly in the response body, either through
a JSON array or as an XML document. For example:

[source,json]
----
[
 {
   "name": "Tony Stark",
   "age": 45,
   "alias": "Iron Man"
 },
 {
   "name": "Steve Rodgers",
   "age": 95,
   "alias": "Captain America"
 },
 {
   "name": "Dr. Stephen Strange",
   "age": 40,
   "alias": "Sorcerer Supreme"
 }
]
----

Others return a complex object with metadata in which the page is
another field:

[source,json]
----
{
 "data": [
   {
     "name": "Tony Stark",
     "age": 45,
     "alias": "Iron Man"
   },
   {
     "name": "Steve Rodgers",
     "age": 95,
     "alias": "Captain America"
   },
   {
     "name": "Dr. Stephen Strange",
     "age": 40,
     "alias": "Sorcerer Supreme"
   }
 ],
 "totalResults": 9
}
----

As such, Connector Descriptors must provide a
Dataweave expression to be evaluated over the response to obtain the
page data. Notice that the expression should return the page. The
expression doesn’t need to be able to split the elements; REST SDK does
that automatically.

For the first example, the expression is `#[payload]` and the second one
is `#[payload.data]`.

== Shop Connector Example

The example Shop connector has a paged content search, so you can define
a pagination strategy in the Connector Descriptor by creating a
pagination node inside the `paginations` property, which is located at
the root of the document.

[source,yaml]
----
#% Rest Connect Connector Descriptor 1.0

apiSpec:
 url: http://myhost.com/resources/shop-api.yaml

connectorName: Shop Connector

connectorGav:
 groupId: com.mulesoft.connectors
 artifactId: shop-connector
 version: 1.0.0

baseUri:
 value: https://myhost.com/shop/api
 type: parameter

paginations:
 content-search-pagination: #Declares a pagination strategy to be used within this API
   type: offset
   parameters:
     offsetParamName: "start"
     initialOffset: 0
     pagingResponse:
       language: "dataweave"
       expression: "#[payload.hits]"

endpoints:
  /content_search:
   operations:
     get:
       pagination: content-search-pagination
----

The example defines an offset based pagination. It declares that the
offset parameter in the API spec is named `start`, and an expression that
allows the connector to extract the results from the response.

You must also define that the content search operation uses that
pagination strategy.
