= Getting Started
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

To create a connector using Rest SDK:

* Use a _mojo_ (Maven plain Old Java Object) to scaffold a connector descriptor for an API Spec.
* Use a mojo to create a Connector from an API Spec and a connector descriptor.
* Perform some modifications to the connector descriptor for tailoring the generated connector.
* Package the connector using Maven.
* Publish the connector to Anypoint Exchange.

== Prerequisites

* Java 8 SDK
* Apache Maven (3.3.9 or newer recommended)

== Install the Rest SDK Plugin

A _mojo_ is a Maven plain Old Java Object.
Each mojo is an executable goal in Maven, and a _plugin_ is a distribution of one or more related mojos.

If you have access to the MuleSoft's repositories, Maven automatically downloads the plugin when you try to use it.

=== Get Access to MuleSoft's Maven Repository

MuleSoft repositories are public. However, you must to configure Maven to access them.

. Access the settings.xml Maven configuration file. +
For Mac or Linux: `Mac/Linux: ~/.m2/settings.xml` +
For Windows: `C:\Users\<UserName>\.m2\settings.xml`
. In `settings.xml`, add a new plugin repository to the `<profile>` section. For example: +
[source,xml]
----
    <profiles>
        <profile>
            <id>default-profile</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <pluginRepositories>
                <pluginRepository>
                    <id>mulesoft-releases</id>
                    <name>Mule Releases Repository</name>
                    <url>https://repository.mulesoft.org/nexus/content/repositories/releases/</url>
                </pluginRepository>
            </pluginRepositories>

        </profile>
    </profiles>
----

You can now use Rest SDK.

== Connector Descriptor

A _connector descriptor_ is a YAML file that allows you to describe a
connector, customize aspects of the generated connector (such as name,
Maven GAV, operation names, layout information, and so on), and provide
additional metadata that is specific to MuleSoft’s connectors.

When you create a connector descriptor, you should not edit the API
spec. If you modify your API spec and a new version of an API spec is
released, you must move all changes from the old version to the new
version. API specs should be as complete as possible and provide rich
schemas for every input/output type, examples, security information, and
so on.

=== Scaffold the Connector Descriptor

To scaffold the connector descriptor, you must run the
`createDescriptor` mojo:

----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createDescriptor -DapiSpec=<PATH_TO_SPEC>/api.raml
----

* Where `<PATH_TO_SPEC>` is the path to the location of your API spec.
* Where `<PLUGIN_VERSION>` is the version of the Rest SDK Plugin you want to use.
If you omit this parameter, the latest version is used.

The `createDescriptor` mojo uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes |The relative path to the API spec for which you want to
create a connector descriptor. |-

|specFormat |No a|
The format of the API spec.

Allowed values are RAML, JsonOAS, YamlOAS, JsonOAS3 and YamlOAS3. For specFormats that are not supported, use https://www.apimatic.io/transformer/[API Transformer] by APIMatic to transform them into RAML or OAS to use the tooling provided by REST SDK.
|If not specified, it will autodetect the format based on the file extension and content.

|outputDir |No a|
The path where the connector descriptor is placed.

The generated file is named output.yaml and located in the specified
folder. |Current directory

|descriptorMode |No |The mode in which you want the connector descriptor to be
generated. Allowed values are MINIMAL and VERBOSE. |MINIMAL

|skipValidation |No |Allows you to skip the validation step for the API
specification. Users should not skip the validations as the successful
parsing of an invalid API spec is not guaranteed. Users who skip
validation may experience issues generating the connector descriptor.
|FALSE
|===

=== Create Connector

After you have modified the connector descriptor, you can generate the
connector using the `createConnector` mojo:

----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createConnector -DapiSpec=<PATH_TO_SPEC>/api.raml -Ddescriptor=<PATH_TO_DESCRIPTOR>/descriptor.yaml
----

* Where `<PATH_TO_SPEC>` is the location of your API spec.
* Where `<PATH_TO_DESCRIPTOR>` is the location of your descriptor.
* Where `<PLUGIN_VERSION>` is the version of the Rest SDK Plugin you want to use.
If you omit this parameter, the latest version is used.

The createConnector mojo uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes
|The relative path to the API spec for which you want to
create a connector. |-

|descriptor |Yes
|The relative paths to the connector descriptors that will be used to customize the connector. The value for this parameter can be a single relative path to a connector descriptor or a list of those, split with commas.|-

|specFormat
|No
a|The format of the API spec.

Allowed values are RAML, JsonOAS, YamlOAS, JsonOAS3, and YamlOAS3. For specFormats that are not supported, use https://www.apimatic.io/transformer/[API Transformer] by APIMatic to transform them into RAML or OAS to use the tooling provided by REST SDK.

|If not specified, it will autodetect the format based on the file extension and content.

|outputDir
|No
a|The path where the connector resides.

The generated file is named `output.yaml` and is located in the specified
folder.
|Current directory


|skipValidation
|No
|Allows you to skip the validation step for the API
spec. Users should not skip the validations as the successful parsing of
an invalid API spec is not guaranteed. Users who skip validation may
experience issues generating the connector.
|FALSE


|dynamicMetadata
|No
|Creates backwards compatible Dynamic Metadata for Operations.
|FALSE

|===

== Customization Layer

Composition is defined in a customization layer file, which is an
instance of an existing connector descriptor. When you create a connector using
this file, the connector is versioned and released separately from the base connector.

This enables you to take an immutable version of a connector
and generate net new assets that add new layers of functionality. These newly
generated composite artifacts can have their own release lifecycle and be developed
separately from the base connector.

Using the customization layer enables you to develop new versions of the base connector without
duplicating code. In addition, changes that are made in the new version will
not affect the base version of the connector, nor will it break backwards compatibility.

=== Create Customization Layer

This composition feature is a part of the standard connector creation flow.
The only difference is that multiple connector descriptors can be specified in
the create connector command.

The following example shows what the create connector command looks like:
----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createConnector -DapiSpec=api.raml -Ddescriptor=connector-descriptor.yaml,customization-layer.yaml
----

The descriptors are used in the order they are specified. In this case,
the `connector-descriptor.yaml` is applied first, and is then overwritten by
the `customization-layer.yaml`.

=== Composing Descriptors

When composing standard connector descriptors, the properties declared in a
descriptor override those declared in previous (base) descriptors.

For example, if the connector name and description are set in the first (base) layer
and then the connector _name_ is overwritten in a second descriptor layer, the final generated connector will have the name of the second layer and the description of the first layer.

== What's Next?

xref:rest-sdk/customize-connector-descriptor.adoc[Customize the Connector Descriptor]
