= Getting Started
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

To create a connector using Rest SDK:

* Use a _mojo_ (Maven plain Old Java Object) to scaffold a Connector Descriptor for an API Spec.
* Use a mojo to create a Connector from an API Spec and a Connector Descriptor.
* Perform some modifications to the Connector Descriptor for tailoring the generated connector.
* Package the connector using Maven.
* Publish the connector to Anypoint Exchange.

== Prerequisites

* Java 8 SDK
* Apache Maven (3.3.9 or newer recommended)

== Install the Rest SDK Plugin

A _mojo_ is a Maven plain Old Java Object.
Each mojo is an executable goal in Maven, and a _plugin_ is a distribution of one or more related mojos.

If you have access to the Mulesoft's repositories, Maven automatically downloads the plugin when you try to use it.

=== Get Access to Mulesoft's Maven Repository

Mulesoft repositories are public. However, you must to configure Maven to access them.

. Access the settings.xml Maven configuration file. +
For Mac or Linux: `Mac/Linux: ~/.m2/settings.xml` +
For Windows: `C:\Users\<UserName>\.m2\settings.xml`
. In `settings.xml`, add a new plugin repository to the `<profile>` section. For example: +
[source,xml]
----
    <profiles>
        <profile>
            <id>default-profile</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <pluginRepositories>
                <pluginRepository>
                    <id>mulesoft-releases</id>
                    <name>Mule Releases Repository</name>
                    <url>https://repository.mulesoft.org/nexus/content/repositories/releases/</url>
                </pluginRepository>
            </pluginRepositories>

        </profile>
    </profiles>
----
You can now use Rest SDK.


== Scaffold the Connector Descriptor

To scaffold the Connector Descriptor, you must run the
`createDescriptor` mojo:

----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createDescriptor -DapiSpec=<PATH_TO_SPEC>/api.raml
----

* Where `<PATH_TO_SPEC>` is the path to the location of your API spec.
* Where `<PLUGIN_VERSION>` is the version of the Rest SDK Plugin you want to use.
If you omit this parameter, the latest version is used.

The `createDescriptor` mojo uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes |The relative path to the API spec for which you want to
create a Connector Descriptor. |-

|specFormat |No a|
The format of the API spec.

Allowed values are RAML, JsonOAS, YamlOAS, JsonOAS3 and YamlOAS3 |RAML

|outputDir |No a|
The path where the Connector Descriptor is placed.

The generated file is named output.yaml and located in the specified
folder. |Current directory

|descriptorMode |No |The mode in which you want the connector descriptor to be
generated. Allowed values are MINIMAL and VERBOSE. |MINIMAL

|skipValidation |No |Allows you to skip the validation step for the API
specification. Users should not skip the validations as the successful
parsing of an invalid API spec is not guaranteed. Users who skip
validation might experience issues generating the connector descriptor
and the connector. |FALSE
|===

== Create Connector

After you have modified the Connector Descriptor, you can generate the
connector using the `createConnector` mojo:

----
mvn com.mulesoft.connectivity:rest-sdk-mojo:<PLUGIN_VERSION>:createConnector -DapiSpec=<PATH_TO_SPEC>/api.raml -Ddescriptor=<PATH_TO_DESCRIPTOR>/descriptor.yaml
----

* Where `<PATH_TO_SPEC>` is the location of your API spec.
* Where `<PATH_TO_DESCRIPTOR>` is the location of your descriptor.
* Where `<PLUGIN_VERSION>` is the version of the Rest SDK Plugin you want to use.
If you omit this parameter, the latest version is used.

The createConnector mojo uses the following parameters:

[cols=",,,",options="header",]
|===
|*Parameter* |*Required* |*Description* |*Default Value*
|apiSpec |Yes |The relative path to the API spec for which you want to
create a Connector. |-

|descriptor |Yes |The relative path to the Connector Descriptor that you
created to customize the API spec. |-

|specFormat
|No
a|The format of the API spec.

Allowed values are RAML, JsonOAS, YamlOAS, JsonOAS3, and YamlOAS3
|RAML

|outputDir
|No
a|The path where the connector resides.

The generated file is named `output.yaml` and is located in the specified
folder.
|Current directory


|skipValidation
|No
|Allows you to skip the validation step for the API
spec. Users should not skip the validations as the successful parsing of
an invalid API spec is not guaranteed. Users who skip validation might
experience issues generating the connector descriptor and the connector.
|FALSE


|dynamicMetadata
|No
|Creates backwards compatible Dynamic Metadata for Operations.
|FALSE


|forceContentParameter
|No
|Forces the content parameters names to always be 'content'.
|FALSE
|===

== What's Next?

xref:rest-sdk/customize-connector-descriptor.adoc[Customize the Connector Descriptor]
