= REST SDK
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

REST SDK enables you to create a connector from an API specification (OAS or RAML)
and uses a metadata-driven approach to accelerate connector development. REST SDK
provides a quick and relevant connectivity experience that is easy to use and requires
little to no configuration.

With REST SDK you can:

* Enable instant connectivity via metadata
* Reduce the speed needed to build a new connector from several months to days or minutes
* Provide a unified connector designer that welcomes non-developer users
* Eliminate the need to generate and maintain system specific code and static assets

== How to Use REST SDK

Use the following documentation as a step-by-step guide to build your own
connector using REST SDK.

* // features.adoc, Features in REST SDK

Learn about which features you would like in your REST SDK connector.

* //.adoc, Setup and Installation

Ensure you meet the prerequisites and install the REST SDK plugin.

* //, Scaffold a Connector Descriptor

Scaffold a connector descriptor from an API spec.

* //, Create a Connector

Create a connector from a connector descriptor and an API specification.

* //, Customize Your Connector

Perform modifications to the connector descriptor to customize your generated connector.





Once you've experienced the end-to-end journey with a connector you create, use
the process to plan your own connectivity projects.


== Features in REST SDK

The following features are available in REST SDK:

* Instant connector generation from RAML 1.0, OAS 2.0, and OAS 3.0
* Maven distribution framework
* Paginated operations
* Triggers
* Value providers
* Sample data
* Security scheme support for:
** Basic authentication
** Bearer authentication
** Digest authentication
** Pass-through authentication
** OAuth 2.0 client credentials grant type
** OAuth 2.0 authorization code grant type
* TLS support
* Specific API operation filtering
* Custom headers and query parameters at the global and operation levels
* Global and operation-specific timeouts
* Support for reconnection
* HTTP proxy support
* Automatic error handling
* Support for multiple base URLs
* Ability to modify or extend the generated connector using Java SDK. You can:
** Add additional security schemes
** Customize operations
** Add message sources or expression functions
** Add dynamic DataSense
** Describe custom authentication

On the non-functional side, REST SDK connectors are fully
https://docs.mulesoft.com/mule-sdk/1.1/non-blocking-operations[non-blocking]
and also provide reduced and optimized extension models.


== Differences with Rest Connect

The main differences between the REST SDK and the Rest Connect v1 are:

* Unlike Rest Connect v1 which generates and deploys an unmodifiable
connector, REST SDK generates source code that you can version, modify,
and extend manually.
* REST SDK does not publish the generated connectors automatically. You
can deploy the connector at your convenience.
* REST SDK generated source code uses Java SDK instead of XML source
code.
