= REST SDK
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Using a metadata-driven approach to accelerate connector development, REST SDK
enables you to quickly and easily create a connector from an API specification (OAS or RAML),
requiring little to no configuration.

Using REST SDK results in:

* Instant connectivity via metadata
* A shorter time to create connectors, sometimes from several months to days or minutes
* A unified connector designer that welcomes nondeveloper users
* Elimination of system-specific code and static assets


Follow this path to build your own connector using REST SDK:

. xref:rest-sdk/overview.adoc[Features in REST SDK]
+
Learn about REST SDK features and use cases.

. xref:rest-sdk/setup-and-installation.adoc[Set Up and Install REST SDK]
+
Complete prerequisites and install the REST SDK plugin.

. xref:rest-sdk/scaffold-a-connector-descriptor.adoc[Scaffold a Connector Descriptor]
+
Scaffold a connector descriptor from an API specification.

. xref:rest-sdk/create-a-connector.adoc[Create a Connector]
+
Create a connector from your connector descriptor and an API specification.

. xref:rest-sdk/create-a-customization-layer.adoc[Create a Customization Layer]
+
To add new layers of functionality, optionally create an instance of your existing connector descriptor.

. xref:rest-sdk/customize-your-connector.adoc[Customize Your Connector]
+
Modify the connector descriptor and customization layer to customize your generated connector.

. Build and Publish Your Connector
+
Build your connector using Apache Maven, generate models, and publish your connector to Anypoint Exchange.

. Use Your Connector in Studio or Flow Designer
+
Use your connector directly in either Anypoint Studio or Anypoint Flow Designer.
