= Security Scheme
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

== Ignore a Security Scheme

If your API spec defines a security scheme that you don’t want to be
present in the generated connector, you can use the `ignored` property
in the `security` node of your connector descriptor.

[source,yaml]
----
security:
  passThrough:
    ignored: true
----

In this case, the API spec declares a security scheme named `passThrough`.
The example uses the ignored annotation, so it does not get generated in
the connector descriptor.

== Set a Security Scheme Parameter Friendly Name

You can set friendly names for security scheme parameters using the
`displayName` annotation in the security scheme node of the Connector
Descriptor. You can use the `ignored` property in the `security` node of
your connector descriptor.

[source,yaml]
----
security:
  passThrough:
    headers:
      passThroughHeader:
        displayName: 'Auth Header'
----

In this case, the API spec defines the security scheme name `passThrough`
which has a parameter named `passThroughHeader` defined. The `displayName`
property is assigned the value `Auth Header`.

== Add Parameters for OAuth Authorization

You can define new parameters to be added in the `Authorize` endpoint for
OAuth 2.0 authorization in the descriptor.

[source,yaml]
----
security:
  oauth2:
    queryParameters:
      prompt:
        additional: true
        type: string
        displayName: 'Prompt'
        description: 'Set to consent'
        default: 'consent'
----

In this case, the query parameter `prompt` will be added on the Authorization endpoint.

== Customize OAuth Refresh Token Condition

Refreshing OAuth access tokens with 401 HTTP status errors using the standard
behavior does not work in all scenarios.

Customize this behavior with a refreshTokenCondition expression that
extends an OAuth security scheme. This feature is supported by Mule 4.4.0 or later.

The available expression bindings in refreshTokenCondition are response payload
and response attributes.

The following example illustrates a customized refreshTokenCondition:

[source,yaml]
----
security:
  oauth_2_0:
    headers:
      authorization:
        friendlyName: 'Authorization header'
    queryParameters:
      access_token:
        friendlyName: 'Access token'
    # ...
    refreshTokenCondition:
      language: "dataweave"
      expression: "#[attributes.statusCode == 403]"
----

If there are response errors, the refreshTokenCondition expression will be a
detection condition used to verify if a refresh access token is needed.

Note that this detection support is applied on detected error responses.
It is applied on the presence of 4xx HTTP client errors or 5xx
server errors, but not on 2xx responses.

=== Example

Imagine there is a SaaS Box API that uses a combination of 401 status code and
www-authenticate standard header to represent a response scenario needing
access token refresh, such as:

----
www-authenticate: Bearer realm="Service", error="invalid_token", error_description="The access token provided is invalid."
----

Use customization since not all 401 errors indicate access token expirations.

The following example illustrates a customized refreshTokenCondition for
this scenario:

[source,yaml]
----
security:
  oauth_2_0:
    # ...
    refreshTokenCondition:
      language: "dataweave"
      expression: "#[attributes.statusCode == 401 and (attributes.headers[\"www-authenticate\"] contains \"error=\\\"invalid_token\\\"\")]"
----
