= Security Scheme
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

== Ignore a Security Scheme

If your API spec defines a security scheme that you don’t want to be
present in the generated connector, you can use the `ignored` property
in the `security` node of your connector descriptor.

[source,yaml]
----
security:
  passThrough:
    ignored: true
----

In this case, the API spec declares a security scheme named `passThrough`.
The example uses the ignored annotation, so it does not get generated in
the connector descriptor.

== Set a Security Scheme Parameter Friendly Name

You can set friendly names for security scheme parameters using the
`displayName` annotation in the security scheme node of the Connector
Descriptor. You can use the `ignored` property in the `security` node of
your connector descriptor.

[source,yaml]
----
security:
  passThrough:
    headers:
      passThroughHeader:
        displayName: 'Auth Header'
----

In this case, the API spec defines the security scheme name `passThrough`
which has a parameter named `passThroughHeader` defined. The `displayName`
property is assigned the value `Auth Header`.

== Add Parameters for OAuth Authorization

You can define new parameters to be added in the `Authorize` endpoint for
OAuth 2.0 authorization in the descriptor.
[source,yaml]
----
security:
  oauth2:
    queryParameters:
      prompt:
        additional: true
        type: string
        displayName: 'Prompt'
        description: 'Set to consent'
        default: 'consent'
----

In this case, the query parameter `prompt` will be added on the Authorization endpoint.

== Customizing OAuth refresh token condition

The standard behavior of refreshing OAuth access tokens on the presence of "401" HTTP status errors, falls short in some scenarios.

There is a way to customize this behavior using a refreshTokenCondition expression extending an OAuth security scheme as in:

[source,yaml]
----
security:
  oauth_2_0:
    headers:
      authorization:
        friendlyName: 'Authorization header'
    queryParameters:
      access_token:
        friendlyName: 'Access token'
    # ...
    refreshTokenCondition:
      language: "dataweave"
      expression: "#[attributes.statusCode == 403]"
----

On the presence of response errors, this will be now the detection condition used to verify if a refresh access token is needed.

The available expression bindings in refreshTokenCondition are:

- response payload
- response attributes

Note that this detection support will be applied on detected error responses, this means it will be applied on the presence of http client errors "4xx" or server errors "5xx", but not on "2xx" responses.

=== Example

Let's illustrate its usage in a real world use case:

The SaaS Box API uses a combination of "401" status code and standard header "www-authenticate" as in:
----
www-authenticate: Bearer realm="Service", error="invalid_token", error_description="The access token provided is invalid."
----
to represent a response scenario needing access token refresh.

This scenario requires customization, since not all "401" errors will indicate access token expirations.

A customized refresh token condition could be used to handle it:
[source,yaml]
----
security:
  oauth_2_0:
    # ...
    refreshTokenCondition:
      language: "dataweave"
      expression: "#[attributes.statusCode == 401 and (attributes.headers[\"www-authenticate\"] contains \"error=\\\"invalid_token\\\"\")]"
----

*Observation:*

REST-SDK relays on MuleSoft Runtime to handle refresh token signal and perform automatic reconnection and this feature is available in MuleSoft Runtimes >= 4.4.0.
