= Customize the Connector's Security Scheme
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Configure and customize the security scheme of the connector descriptor of
the connector.

== Set a Display Name for a Security Scheme Parameter

To set a display name for a security scheme parameter, use the
`displayName` property, which is located in the security node.

[source,yaml]
----
security:
  passThrough:
    headers:
      passThroughHeader:
        displayName: 'Auth Header'
----

In this example, the API specification defines the security scheme named `passThrough`,
which defines a parameter named `passThroughHeader`. The `displayName`
property is assigned the value `Auth Header`.

== Ignore a Security Scheme

To ignore a security scheme, use the `ignored` property, which is located
in the security node.

You can ignore a security scheme if your API specification defines a security
scheme that you do not want in the generated connector.

[source,yaml]
----
security:
  passThrough:
    ignored: true
----

In this example, the API specification declares a security scheme named `passThrough`.
The example uses the `ignored` property, so the security scheme is not generated in
the connector descriptor.

== Add Parameters for OAuth 2.0 Authorization

To add parameters for OAuth 2.0 authorization, define the parameters in
the security node.

You can define new parameters to add in the `Authorize` endpoint for
OAuth 2.0 authorization in the connector descriptor.

[source,yaml]
----
security:
  oauth2:
    queryParameters:
      prompt:
        additional: true
        type: string
        displayName: 'Prompt'
        description: 'Set to consent'
        default: 'consent'
----

In this example, the query parameter `prompt` is added in the `Authorize` endpoint.

== Customize the OAuth Refresh Token Condition

To customize the OAuth refresh token condition, use the `refreshTokenCondition`
expression, which extends an OAuth security scheme. This feature is supported by
Mule 4.4 and later.

Refreshing OAuth access tokens with 401 HTTP status errors using the standard
behavior does not work in all scenarios. You can customize this behavior with a
`refreshTokenCondition` expression.

The available expression bindings in the `refreshTokenCondition` expression are
response payload and response attributes.

The following example shows a customized refresh token condition:

[source,yaml]
----
security:
  oauth_2_0:
    headers:
      authorization:
        friendlyName: 'Authorization header'
    queryParameters:
      access_token:
        friendlyName: 'Access token'
    # ...
    refreshTokenCondition:
      language: "dataweave"
      expression: "#[attributes.statusCode == 403]"
----

If there are response errors, the `refreshTokenCondition` expression acts as a
detection condition used to verify if a refresh access token is needed.

This detection support is applied on detected error responses. This detection support
is applied on the presence of 4xx HTTP client errors or 5xx server errors, but it
is not applied on 2xx responses.

=== Example

Suppose there is a SaaS Box API that uses a combination of 401 status code and
www-authenticate standard header to represent a response scenario needing
access token refresh, for example:

----
www-authenticate: Bearer realm="Service", error="invalid_token", error_description="The access token provided is invalid."
----

Use a custom refresh token condition since not all 401 errors indicate access token expirations.

The following example shows a custom refresh token condition for
this scenario:

[source,yaml]
----
security:
  oauth_2_0:
    # ...
    refreshTokenCondition:
      language: "dataweave"
      expression: "#[attributes.statusCode == 401 and (attributes.headers[\"www-authenticate\"] contains \"error=\\\"invalid_token\\\"\")]"
----
