= Simple Composition Patterns
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

There are specific pre-identified use cases that fit a general pattern in the
target API. You can identify these patterns and use declarative metadata to
express them.

== Hiding Parameters

This pattern is used to hide parameters by not declaring them in the
parameters section. Hidden parameters can still be assigned a value through
the bindings section.

== Examples of Hiding Parameters

For example, suppose that instead of a generic
*create-single* operation you want a type specific operation called
*create-lead*. This would be the same as *create-single* but the type
parameter will be hidden and changed to "Lead".

[source,text,linenums]
----
operations:
  adapters:
    create-lead:
      base: createObjects
      displayName: Create Lead
      description: Creates a Lead

      parameters:
        lead:
          displayName: Object
          type:
            inherit: content
          required: true

    binding:
            content:
              expression:
                language: "dw"
                value: "#[[parameters.object]]"
            objectType:
              value: "Lead"

      returns:
        payload:
          expression:
            language: "dw"
            value: "#[payload[0]]"
----

== Changing Parameter Default Values

This pattern involves changing the default value of a parameter. This can be
used for:

* Changing the default value of an optional parameter

* Turning an optional parameter into one that is required (no more default value)

* Turning a required parameter into one that is optional (add a default value)

The use cases described above can all be expressed through a required and
defaultValue directive.

== Examples of Changing Parameter Default Values

=== Making an Optional Parameter Required

Suppose that instead of creating a new object parameter you wanted to reuse
the `content` parameter already present in the base connector. However, you
want to change it from optional with default #[payload] to required.

[source,text,linenums]
----
operations:
  adapters:
    create-single:
      base: createObjects
      displayName: Create Single
      description: Creates one single object

      parameters:
        type:
          displayName: Object Type
          type: string
          required: true

        content:
          displayName: Content
          type:
            inherit: content
          required: true

      binding:
        objectType:
          expression:
            language: "dw"
            value: "#[parameters.type]"
        content:
          expression:
            language: "dw"
            value: "#[[parameters.object]]"

      returns:
        payload:
          expression:
            language: "dw"
            value: "#[payload[0]]"
----

By specifying that the `content` parameter is now required and maps to the
original content parameter, you make the parameter required and remove
the default value.

=== Making a Required Parameter Optional

Consider the opposite case of the <<Making an Optional Parameter Required, previous example>>.
Suppose you want to redefine the `type` parameter and make it optional and default to "Lead".

[source,text,linenums]
----
operations:
  adapters:
    create-single:
      base: createObjects
      displayName: Create Single
      description: Creates one single object

      parameters:
        type:
          displayName: Object Type
          type: string
          required: false
          defaultValue: "Lead"

        content:
          displayName: Content
          type:
            inherit: content
          required: true

      binding:
        objectType:
          expression:
            language: "dw"
            value: "#[parameters.type]"
        content:
          expression:
            language: "dw"
            value: "#[[parameters.object]]"

      returns:
        payload:
          expression:
            language: "dw"
            value: "#[payload[0]]"
----
