= Customize Composer Connectors
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

== About Composition

Composition enables you to take an immutable version of a connector
and generate net new assets that add new layers of functionality. These newly
generated composite artifacts can have their own release lifecycle and be developed
separately from the base connector.

Using composition enables you to develop new versions of the base connector without duplicating code. In addition, changes that are made in the Composer version will not affect the base version of the connector, nor will it break backwards compatibility.

== Simple Composition

Use simple composition for Composer connectors to automatically
generate connectors based on REST SDK metadata in the Composer UI.

Use cases for simple composition can be generalized into standard patterns, such as transforming input and output types or hiding top level parameters.

These patterns:

* Are agnostic of the target system domain model
* Are easily expressed through declarative metadata
* Include components from one single connector
