= Simple Composition Patterns
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

There are specific pre-identified use cases that fit a general pattern in the target API. You can identify these patterns and use declarative metadata to express them.

=== Generalization

This pattern can be generalized as one that composes of one operation with a set of input or output transformations. The operation exposes only a subset of the parameters of the base operation and can change each parameter's signature, for example, the name, default value, or type.
The operation can also add additional custom parameters. A binding transformation maps each of the composed operation parameters to those of the base operation. A transformation can also be used optionally to change the output type.

==== Examples of Generalization

===== Salesforce Create Single

This example exposes a reduced set of parameters. The bindings section transforms the single object into a one element array.
The output is also transformed by returning the first item in the response array.

[source,text,linenums]
----
adapters:
  create-single:
  path: /createObjects/{objectType}
  method: POST
  displayName: Create Single
  description: Creates one single object

  parameters:
    type:
      displayName: Object Type
      type: string
      required: true
    object:
      displayName: Object
      type: object
      required: true

  binding:
    uriParameter:
      objectType:
        value: "#[parameters.type]"
    body:
      expression: '#[[parameters.object]]'

  returns:
    payload:
      expression: "#[payload[0]]"
----

===== Gmail Get Messages

This example exposes one parameter with a different default value. The result payload and attributes are combined into a single option, and the operation is changed to return no attributes.
