= Simple Composition Patterns
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

There are specific pre-identified use cases that fit a general pattern in the
target API. You can identify these patterns and use declarative metadata to
express them.

== Hiding Operations

This pattern is used to hide operations. Operations declared in a previous layer
can be hidden by ignoring them in a descriptor layer.

For example, take the following descriptor as the base layer:
----
#% Rest Connect Connector Descriptor 1.0

apiSpec:
 url: http://myhost.com/resources/shop-api.yaml

connectorName: Shop Connector

connectorGav:
 groupId: com.mulesoft.connectors
 artifactId: shop-connector
 version: 1.0.0
----

This will generate all the operations of the connector declared in the API specification.
To generate a connector with only a subset of the operations while also maintaining
all the customizations declared in this descriptor, a new descriptor layer can be used:

----
#% Rest Connect Connector Descriptor 1.0

connectorGav:
 groupId: com.mulesoft.connectors
 artifactId: composed-shop-connector
 version: 1.0.0

endpoints:
    /users:
        ignored: true
----

All the operations under the '/users' endpoint are ignored and are not present
in the generated connector.

== Renaming Operations

This pattern is used to customize operation names.

For example, take the following descriptor as the base layer:

----
#% Rest Connect Connector Descriptor 1.0

apiSpec:
 url: http://myhost.com/resources/shop-api.yaml

connectorName: Shop Connector

connectorGav:
 groupId: com.mulesoft.connectors
 artifactId: shop-connector
 version: 1.0.0

endpoints:
    /users:
        operations:
            get:
                displayName: Get Users
----

The `Get Users` operation can be renamed to `Get All Users` in the descriptor:

----
#% Rest Connect Connector Descriptor 1.0

connectorGav:
 groupId: com.mulesoft.connectors
 artifactId: composed-shop-connector
 version: 1.0.0

endpoints:
    /users:
        operations:
            get:
                displayName: Get All Users
----

The operation is now renamed in the generated connector.
