= Customize the Connector's Triggers
ifndef::env-site,env-github[]
include::../_attributes.adoc[]
endif::[]

Configure and customize a trigger of the connector descriptor of the connector.

[IMPORTANT]
Because triggers work with a xref:polling-sources[polling source] on the backend,
the items must be in ascending order (from older to newer) so that the extraction
of the watermark contains the correct date.

== Declare a Trigger

The following example shows the declaration of a trigger, or a polling source, for
the following endpoint from the Salesforce Sales Cloud API.

----
GET /vXX.X/sobjects/{SObjectName}/updated/?start=startDateAndTime
----

This endpoint returns a list of the specified *{SObjectName}* updated since the
provided start query parameter.

This endpoint needs a trigger declaration. The trigger must initiate a new event
and act as a source for a flow for every record that is updated.

The following example shows what a response from the endpoint looks like:

[source,json5]
----
{
"items" : [
{"id": "a00D0000008pQR5IAM"/*, [...]*/},
{"id": "a00D0000008pQRGIA2"/*, [...]*/},
{"id": "a00D0000008pQRFIA2"/*, [...]*/},
],
"latestDateCovered" : "2013-05-08T21:20:00.000+0000"
}
----

The following example shows what a trigger declaration looks like:

[source,yaml]
----
triggers:
   onUpdatedObject:
     path: /v48.0/sobjects/{SObjectName}/updated/
     method: get
     displayName: SObjects Updated
     description: Query for updated instances of a specified SObject

     outputType: ./SObject.json
     outputMediaType: application/json

     parameters:
       objectName:
         displayName: SObject Name
         description: The object to query for new records
         type: string
         required: true
       startDate:
         displayName: Start Date
         description: The date since an element has to have been modified in order to trigger.
         type: localDateTime
         required: true

     binding:
       uriParameter:
         SObjectName:
            value: "#[parameters.objectName]"
       queryParameter:
         start:
           value: "#[if(context.watermark == null) parameters.startDate else context.watermark]"

     items:
       extraction:
         expression: "#[payload.items]"

     watermark:
       extraction:
         expression: "#[payload.latestDateCovered]"
      type: localDateTime


     identity:
       extraction:
         expression: "#[item.id]"
----

The following table shows a detailed explanation of each part of the
trigger declaration:

`triggers`::
The section of the connector descriptor in which all triggers must be declared.

`onUpdatedObject`::
The name of this trigger. The generated class name is generated based on this. It
must be unique.

`path`::
The path that is polled to check if a new event must be triggered. If an object
has been updated, in this case -, it gets the mentioned updated entities.

`method`::
Defines the HTTP verb that is used when making this request.

`displayName`::
Defines a name that the user sees.

`description`::
Define a description that the user sees.

`outputType`::
The property that defines the trigger output metadata. It must be a path to a
JSON schema, relative to the connector descriptor file location.

`outputMediaType`::
The property that overrides the trigger default output media type that comes
from the API specification.

`parameters`::
Defines the parameters that the user sees. The parameters do not need to be the
same as those the API endpoint declares.

`objectName`::
In this case, the user should choose the SObject they want to query, so the
*objectName* parameter exists for the user to provide that name.

`displayName`::
Defines a name for the parameter that the user sees.

`description`::
Defines a description for the parameter that the user sees.

`type`::
Defines the type of data that the parameter stores. Adds restrictions to what the
user can input. Allowed values for the `type` field are integer, number, string,
localDateTime, zonedDateTime, and boolean.

`required`::
Indicates whether the user must give a value to this parameter. The default value
for `required` is true, so if you do not want to force the user to specify a value
for this parameter, you must set `required` to false.

`startDate`::
The user must provide a start date from where to start querying for updates. The
`startDate` parameter fulfills this requirement.

`displayName`::
Defines a name for the parameter that the user sees.

`description`::
Defines a description for the parameter that the user sees.

`type`::
Defines the type of data that the parameter stores. In this case, the `type` is
localDateTime. This matches the watermark type, and it receives the watermark as
its initial value.

`required`::
Indicates whether the user must give a value to this parameter. The default value
for `required` is true, so if you do not want to force the user to specify a value
for this parameter, you must set `required` to false.

`binding`::
Defines the parameters values to send in the request.

`uriParameter`::
There are context variables and the parameters values the user set available to
use. Each expression in a trigger has access to a different set of the context
variables, specified in the *Trigger Expressions* section.

`SObjectName`::
First, you can send the SObjectName set by the user in the request, so you can bind
the `SObjectName URI parameter` to the `objectName` parameter.

`value`::
The `objectName` parameter is declared using the `"#[parameters.objectName]"`
expression.

`queryParameter`::
Send the start query parameter in a way that allows the trigger to
query for new records each time.

`start`::
If it is not set, use the startDate provided by the user for the `start` query parameter,
as it is the first date to query in this example.

`value`::
For this, check if the watermark is set. This happens if the trigger polled
values previously. You can then send it.

`items`::
Defines how to extract the actual values from the server response.

In this case, the response looks like this:
+
[source,json5]
----
{
"items" : [
{"id": "a00D0000008pQR5IAM"/*, [...]*/},
{"id": "a00D0000008pQRGIA2"/*, [...]*/},
{"id": "a00D0000008pQRFIA2"/*, [...]*/},
],
"latestDateCovered" : "2013-05-08T21:20:00.000+0000"
}
----
+
The trigger automatically splits the array, and each of the items is sent to the
flow as a different element. For example, `{"id": "a00D0000008pQR5IAM", [...]}` is
one of the propagated items.

`extraction`::
Used to extract the array.

`expression`::
Extract the array using the `"#[payload.items]` expression.

`watermark`::
Defines how to extract the watermark from the response and how to check if the
extracted watermark is higher than the actual one. If it is higher, it is
set as the new watermark.

In this case, the response provides the last covered date in a separate field,
so you can simply get the date from there.

`extraction`::
Used to extract the watermark.

`expression`::
Extract the watermark using the `#[payload.latestDateCovered]` expression to extract
the date from the latestDateCovered response field.

`type`::
Defines the type of data that the watermark stores. In this case, the `type` is
localDateTime. This matches the parameter type.

`identity`::
Sets the `item id`, or each instance of an element from the split payload, as an
identity. By setting this value, each `id` triggers only an event once per poll.
If the `id` appears more than once, the application is not notified.

`extraction`::
Used to extract the identity.

`expression`::
Extract the identity using the `#[item.id]` expression.

== Ignore a Trigger

To ignore a trigger that was declared on a previous layer,
you must use the `ignored` property:

[source,yaml]
----
triggers:
   myTrigger:
     ignored: true
----

The trigger, *myTrigger*, is ignored and is not generated.

== Ignore Operations and Triggers by Default

To ignore operations and triggers by default, you must use the `ignoreOperations`
property, which is located at the root of the connector descriptor.

Set the `ignoreOperations` property to `true` to ignore previously declared
operations and triggers. You can use this property to select only a small subset
of operations and triggers for the connector to generate.

If an operation or trigger is ignored in a previous layer but `ignoreOperations`
is set to `false`, the operation or trigger will be generated in the connector.

If an operation or trigger is not ignored in a previous layer but `ignoreOperations`
is set to `true`, the operation or trigger will not be generated in the connector.

[source,yaml]
----
#% Rest Connector Descriptor 1.0

ignoreOperations: true

endpoints:
   /flights/{ID}:
      ignored: false
----

In this example, only the operations and triggers under the `/flights/{ID}` path are generated.
All of the other operations and triggers are ignored.

Using the `ignoreOperations` property is similar to adding an `ignored` property
to all of the operations and triggers.

== Trigger Expressions

Wherever an expression is supported, you can provide the described expression
object or a simple string value.

When a string value is provided, REST SDK checks if it is an expression or a
fixed value and behaves accordingly.

Depending on the context, the expressions have access to the following variables:

[cols="h,l"]
|===
|Variable Name | Description

|parameters
|Contains a map of the parameters declared for the trigger and their assigned values.

|context.watermark
|Contains the value of the current watermark. This value is null in the first poll. Subsequent polls contain the highest value extracted from the previous polls.

|payload
|The full response returned from the server.

|attributes
|The response attributes returned from the server. These attributes look like attributes from a request done using HTTP Connector.

|item
|When the response from the server is extracted and split, the `item` variable contains each of those split values.

|===

The availability of these variables depending on the expressions is as follows:

[cols="h,l,l,l,l,l"]
|===
| | parameters | context.watermark | payload | attributes | item

| Parameter Binding
| Yes
| Yes
| -
| -
| -

| Body Binding
| Yes
| Yes
| -
| -
| -

| Watermark Extraction
| Yes
| Yes
| Yes
| Yes
| Yes

| Items Extraction
| Yes
| Yes
| Yes
| Yes
| -

| Identity Extraction
| Yes
| Yes
| Yes
| Yes
| Yes

|===
